---
galaxy_info:
  author: Dave Konopka
  description: Setup core AWS infrastructure
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
      - trusty
dependencies: []
  
